package edu.cotarelo.views;

import edu.cotarelo.dao.mysql.MySQLClubDAO;
import edu.cotarelo.dao.objects.ClubDAO;
import edu.cotarelo.domain.Club;
import edu.cotarelo.fonts.Fuentes;
import java.awt.Color;
import java.awt.HeadlessException;
import javax.naming.NamingException;

public class RegistrarClub extends javax.swing.JPanel {

    Fuentes tipoFuente;

    public RegistrarClub() {
        initComponents();
        InitStyles(false, null);
    }

    RegistrarClub(Club club) {
        initComponents();
        InitStyles(true, club);
    }

    private void InitStyles(boolean isEdition, Club club) {
        tipoFuente = new Fuentes();

        title.setFont(tipoFuente.fuente(tipoFuente.roBold, 0, 22));
        title.setForeground(Color.black);
        nameClubLbl.setFont(tipoFuente.fuente(tipoFuente.roRegular, 0, 14));
        nameClubLbl.setForeground(Color.black);
        descLbl.setFont(tipoFuente.fuente(tipoFuente.roRegular, 0, 14));
        descLbl.setForeground(Color.black);
        campoLbl.setFont(tipoFuente.fuente(tipoFuente.roRegular, 0, 14));
        campoLbl.setForeground(Color.black);

        nameClubTxt.setFont(tipoFuente.fuente(tipoFuente.roRegular, 0, 12));
        descTxt.setFont(tipoFuente.fuente(tipoFuente.roRegular, 0, 12));
        campoTxt.setFont(tipoFuente.fuente(tipoFuente.roRegular, 0, 12));
        btn_subir.setFont(tipoFuente.fuente(tipoFuente.roBold, 0, 18));

        
        if (isEdition) {
            title.setText("Editar Club");
            btn_subir.setText("Guardar");
        // Si estamos en modo edición, se actualizan los campos de texto con los datos del jugador existente.
            if (club != null) {
                nameClubTxt.setText(club.getNombre());
                descTxt.setText(club.getDescripcion());
                campoTxt.setText(club.getCampo());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        nameClubLbl = new javax.swing.JLabel();
        nameClubTxt = new javax.swing.JTextField();
        descLbl = new javax.swing.JLabel();
        descTxt = new javax.swing.JTextField();
        campoLbl = new javax.swing.JLabel();
        campoTxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btn_subir = new javax.swing.JButton();
        imgPageRC = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setPreferredSize(new java.awt.Dimension(750, 150));

        title.setText("Alta nuevo Club");

        nameClubLbl.setText("Nombre");

        descLbl.setText("Descripción");

        campoLbl.setText("Campo");

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setPreferredSize(new java.awt.Dimension(200, 10));

        btn_subir.setBackground(new java.awt.Color(18, 90, 173));
        btn_subir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_subir.setForeground(new java.awt.Color(255, 255, 255));
        btn_subir.setText("Subir");
        btn_subir.setBorderPainted(false);
        btn_subir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_subir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_subirActionPerformed(evt);
            }
        });

        imgPageRC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/cotarelo/imagenes/EscudoEspaña.png"))); // NOI18N

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameClubTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(descTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameClubLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(descLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(btn_subir, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addComponent(imgPageRC, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(title)
                        .addGap(18, 18, 18)
                        .addComponent(nameClubLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameClubTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(descLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(descTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btn_subir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(imgPageRC, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_subirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_subirActionPerformed
        String nombre = nameClubTxt.getText();
        String desc = descTxt.getText();
        String campo = campoTxt.getText();

        // Validaciones para los campos
        if (nombre.isEmpty() || desc.isEmpty() || campo.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe llenar todos los campos. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            nameClubTxt.requestFocus();
            return;
        }

        Club club = new edu.cotarelo.domain.Club();
        club.setNombre(nombre);
        club.setDescripcion(desc);
        club.setCampo(campo);

        try {
            ClubDAO dao = new MySQLClubDAO();
            dao.insertar(club);

            javax.swing.JOptionPane.showMessageDialog(this, "Club dado de alta exitosamente. \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);

            nameClubTxt.setText("");
            descTxt.setText("");
            campoTxt.setText("");
        } catch (HeadlessException | NamingException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un error al dar de alta al club. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btn_subirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton btn_subir;
    private javax.swing.JLabel campoLbl;
    private javax.swing.JTextField campoTxt;
    private javax.swing.JLabel descLbl;
    private javax.swing.JTextField descTxt;
    private javax.swing.JLabel imgPageRC;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel nameClubLbl;
    private javax.swing.JTextField nameClubTxt;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
